MaxEventSize = 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data

[Writable]
LogLevel = "INFO"

[Service]
Port = 59986
StartupMsg = "device rest started"

[MessageBus]
  [MessageBus.Optional]
  # Default MQTT & NATS Specific options that need to be here to enable environment variable overrides of them
  ClientId = "device-rest"

# Driver configs
[Driver]
