MaxEventSize: 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data

Writable:
  LogLevel: INFO

# uncomment when running from command-line in hybrid mode with -cp -o flags
#Registry:
# Host: localhost
#
#Clients:
# core-metadata:
#   Host: localhost

Service:
  Host: localhost
  Port: 59986
  StartupMsg: device rest started

MessageBus:
#  Host: localhost # uncomment when running from command-line in hybrid mode
  Optional:
    ClientId: device-rest

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"