MaxEventSize = 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data

[Writable]
LogLevel = "INFO"

[Service]
Port = 59986
StartupMsg = "device rest started"

[MessageBus]
  [MessageBus.Topics]
  PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  DeviceCommandRequestTopic = "edgex/device/command/request/device-rest/#"   # subscribing for inbound command requests
  ResponseTopicPrefix = "edgex/response" # /<service-name>/<request-id> will be added to this prefix topic
  [MessageBus.Optional]
  # Default MQTT & NATS Specific options that need to be here to enable environment variable overrides of them
  ClientId = "device-rest"

[SecretStore]
Type = "vault"
Host = "localhost"
Port = 8200
Path = "device-rest/"
Protocol = "http"
RootCaCertPath = ""
ServerName = ""
SecretsFile = ""
DisableScrubSecretsFile = false
TokenFile = "/tmp/edgex/secrets/device-rest/secrets-token.json"
  [SecretStore.Authentication]
  AuthType = "X-Vault-Token"
  [SecretStore.RuntimeTokenProvider]
  Enabled = false
  Protocol = "https"
  Host = "localhost"
  Port = 59841
  TrustDomain = "edgexfoundry.org"
  EndpointSocket = "/tmp/edgex/secrets/spiffe/public/api.sock"
  RequiredSecrets = "redisdb"

# Driver configs
[Driver]
