# Pre-define Devices
[[DeviceList]]
  Name = "ED_ID1"
  ProfileName = "ED_ID1"
  Description = "RESTful Device that sends data"
  Labels = [ "rest", "ED_ID1" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.EndDevice_Params]
	  ED_IP = "127.0.0.1"
	  ED_PORT = "5000"
	  #ED_URI_Prefix = ""
	  ED_URI_Prefix = "api"
  [[DeviceList.AutoEvents]]
    Interval = "20s"
    OnChange = false
    SourceName = "jsonRes"
