# Pre-define Devices
[[DeviceList]]
  Name = "sample-json"
  ProfileName = "sample-json"
  Description = "RESTful Device that sends in JSON data"
  Labels = [ "rest", "json" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "sample-image"
  ProfileName = "sample-image"
  Description = "RESTful Device that sends in binary image data"
  Labels = [ "rest", "binary", "image" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "sample-numeric"
  ProfileName = "sample-numeric"
  Description = "RESTful Device that sends in numeric data"
  Labels = [ "rest", "numeric", "float", "int" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "2way-rest-device"
  ProfileName = "sample-2way-rest-device"
  Description = "RESTful Device that sends data"
  Labels = [ "rest", "2way-rest-device" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.REST]
	  Host = "127.0.0.1"
	  Port = "5000"
	  Path = "api"
  #[[DeviceList.AutoEvents]]
  #  Interval = "20s"
  #  OnChange = false
  #  SourceName = "int8"
